[meta]
description = "Grammar extension for natural language referencing of context files/dirs across multiple projects using @@<project-names>:<module-type>."
purpose = "Enable succinct, cross-project references leveraging shared module taxonomy."

[syntax]
pattern = "@@<project-names>:<module-type>"
project_names = "Comma-separated list of project or corpus names"
module_type = "Directory or module type (e.g., layouts, components, config)"

[examples]
single = "@@gideon:layouts"
multiple = "@@gideon,blackprint,logos:components"
nested = "@@desirtechnology,gideon:src/config"

[explanation]
shared_architecture = "This syntax works because all projects use the same linguistic architecture and module taxonomy, so module types are consistent and can be referenced in aggregate."

[usage]
instructions = [
  "To refer to all 'layouts' directories in gideon and blackprint, use: @@gideon,blackprint:layouts",
  "For all 'components' across desirtechnology and logos: @@desirtechnology,logos:components"
]
