version: "3.9"

services:
  nextjs-app:
    build:
      dockerfile: Dockerfile
      target: ${TARGET:-development}
    ports:
      - "3000:3000"
    volumes:
      -.:/app:cached
      - next_cache:/app/.next
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_MY_ENV_VAR=${NEXT_PUBLIC_MY_ENV_VAR} # Replace with your env variable
    depends_on: # If you have other services like a database
      # - database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

