// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_route_ from "./routes/[...route].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_sitemap from "./routes/api/sitemap.ts";
import * as $index from "./routes/index.tsx";
import * as $index_1 from "./islands/index.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...route].tsx": $_route_,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/sitemap.ts": $api_sitemap,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/index.ts": $index_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
