[metadata]
name="Desir Technology"
version = "0.0.1"
author = "Jeffrey Jonathan Desir"
date = "2025-04-05"




[models]
definition = "Models configuration"


[views]
definition = "Views configuration"
 

[controllers]