[[main]]
name = "Home"
url = "/"

[[main]]
name = "About"
url = "/about"

[[main]]
name = "Docs"
url = "/docs"

[[main]]
name = "Blog"
url = "/blog"

[[main]]
name = "Recipes"
url = "/recipes"

[[main]]
name = "Poetry"
url = "/poetry"

[[main]]
name = "Index Cards"
url = "/index-cards"

[[main]]
name = "Authors"
url = "/authors"