# UI Taxonomy for Tesseract-based Component System

# Meta section documents the philosophy and Tesseract relation
[meta]
description = "A multidimensional taxonomy for UI primitives and components, designed for variant dispatch and composability. Inspired by the Tesseract concept: every UI element is a base type, and variants are dispatched as orthogonal dimensions."
tesseract_relation = "Elements are base dimensions; variants are axes of modification, enabling composable, multidimensional UI construction."

# Canonical UI element types - organized by semantic purpose
[[elements]]
category = "structural"
description = "Core page structure elements"
names = ["Header", "Footer", "Nav", "Section", "Article", "Aside", "Main"]

[[elements]]
category = "typography"
description = "Text and typography elements"
names = ["H1", "H2", "H3", "H4", "H5", "H6", "Paragraph", "Span", "Blockquote", "Pre", "Code"]

[[elements]]
category = "interactive"
description = "User input and interactive elements"
names = ["Button", "Input", "Label", "Form", "Select", "Textarea", "Checkbox", "Radio", "ToggleSwitch"]

[[elements]]
category = "media"
description = "Media and visual elements"
names = ["Image", "Video", "Audio", "Icon"]

[[elements]]
category = "containers"
description = "Basic content containers"
names = ["Div", "List", "ListItem", "Link", "Divider"]

# Higher-level, reusable UI components - organized by purpose and complexity
[[components]]
category = "content_containers"
description = "Components that primarily contain and display content"
names = ["Card", "InfoCard", "SimpleCard", "HolographicInfoCard", "Panel", "Surface", "Paper"]

[[components]]
category = "overlays"
description = "Components that overlay the main UI"
names = ["Modal", "Dialog", "Popover", "Tooltip", "Snackbar", "Toast", "Alert"]

[[components]]
category = "navigation"
description = "Components for navigating the UI"
names = ["Accordion", "Tabs", "Dropdown", "Menu", "Breadcrumbs", "Pagination", "Sidebar", "Navbar", "Drawer"]

[[components]]
category = "data_display"
description = "Components for displaying structured data"
names = ["Table", "DataGrid", "TreeView", "Chart", "Map", "Carousel", "List", "Timeline"]

[[components]]
category = "feedback"
description = "Components that provide user feedback"
names = ["ProgressBar", "ProgressCircle", "Spinner", "Skeleton", "Badge", "Chip", "Tag", "TagGroup"]

[[components]]
category = "inputs"
description = "Advanced input components"
names = ["SearchBar", "Slider", "DatePicker", "TimePicker", "ColorPicker", "FileUpload", "RichTextEditor"]

[[components]]
category = "media"
description = "Media-related components"
names = ["Avatar", "AvatarGroup", "MediaCard", "Gallery", "Carousel"]

# Includes: partials, reusable fragments - organized by purpose
[[includes]]
category = "branding"
description = "Brand identity elements"
names = ["Logo", "Branding", "BrandColors", "Tagline"]

[[includes]]
category = "navigation"
description = "Navigation elements"
names = ["Menu", "Navigator", "UserMenu", "MainNav", "FooterNav", "HeaderNav", "SidebarNav"]

[[includes]]
category = "input"
description = "Input-related includes"
names = ["SearchBar", "FormFields", "FieldLabel", "FieldError", "FieldGroup", "FieldHelp"]

[[includes]]
category = "content_display"
description = "Content display includes"
type = "container"
names = ["ContentCollection", "CallToAction"]

[[includes.content_display]]
type = "grid"
names = ["GridList", "Gallery", "CardGrid", "FeatureGrid"]

[[includes.content_display]]
type = "list"
names = ["VerticalList", "HorizontalList", "Timeline", "Feed"]

[[includes.content_display]]
type = "table"
names = ["DataTable", "PriceTable", "ComparisonTable", "SpecsTable"]

[[includes.content_display]]
type = "navigation"
names = ["Breadcrumbs", "Pagination", "SocialLinks", "RelatedContent"]

# Layouts: page or section-level structure - organized by purpose
[[layouts]]
category = "page"
description = "Full-page layouts"
names = ["DefaultLayout", "DashboardLayout", "AuthLayout", "LandingLayout", "BlogLayout", "DocsLayout"]

[[layouts]]
category = "structure"
description = "Section-level structural layouts"
names = ["SidebarLayout", "SplitLayout", "GridLayout", "HeroLayout", "MasterDetailLayout"]

[[layouts]]
category = "arrangement"
description = "Content arrangement layouts"
names = ["MasonryLayout", "CenteredLayout", "FullWidthLayout", "SplitWithSidebarLayout", "StackedLayout"]

[[layouts]]
category = "responsive"
description = "Responsive behavior specifications"
breakpoints = ["mobile", "tablet", "desktop", "widescreen"]
strategies = ["stack", "reflow", "hide", "resize"]

# Containers: wrappers and compositional primitives - organized by purpose
[[containers]]
category = "basic"
description = "Basic layout containers"
names = ["Box", "Container", "SectionContainer", "Wrapper", "Viewport"]

[[containers]]
category = "flex"
description = "Flexbox-based containers"
names = ["Flex", "Stack", "StackVertical", "StackHorizontal", "Row", "Column"]

[[containers]]
category = "grid"
description = "Grid-based containers"
names = ["Grid", "GridItem", "AutoGrid", "ResponsiveGrid"]

# Linguistic algebra for variants (not part of base name, but dispatched as options)
[variants]
axes = [
  "Style",     # e.g. Simple, Holographic, Outlined, Filled, Glassmorphic
  "Purpose",   # e.g. Info, Action, Warning, Success, Danger
  "Size",      # e.g. Small, Medium, Large, XL
  "State",     # e.g. Disabled, Loading, Active, Selected
  "Shape",     # e.g. Rounded, Square, Pill, Circle
  "Animation", # e.g. Fade, Slide, Pop, Holographic
  "Density",   # e.g. Compact, Comfortable, Spacious
  "Theme"      # e.g. Light, Dark, Neon, Pastel
]

# Example variant values with descriptions
[[variant_values]]
axis = "Style"
description = "Visual styling of the component"
values = ["Simple", "Holographic", "Outlined", "Filled", "Glassmorphic", "Neumorphic", "Gradient"]

[[variant_values]]
axis = "Purpose"
description = "Semantic purpose/meaning of the component"
values = ["Info", "Action", "Warning", "Success", "Danger", "Primary", "Secondary", "Tertiary"]

[[variant_values]]
axis = "Size"
description = "Size variants of the component"
values = ["XS", "Small", "Medium", "Large", "XL", "2XL", "Responsive"]

[[variant_values]]
axis = "State"
description = "Interactive state of the component"
values = ["Default", "Disabled", "Loading", "Active", "Selected", "Focused", "Hovered"]

[[variant_values]]
axis = "Shape"
description = "Geometric shape of the component"
values = ["Rounded", "Square", "Pill", "Circle", "Custom"]

[[variant_values]]
axis = "Animation"
description = "Animation style applied to the component"
values = ["None", "Fade", "Slide", "Pop", "Holographic", "Morph", "Pulse"]

[[variant_values]]
axis = "Density"
description = "Content density of the component"
values = ["Compact", "Comfortable", "Spacious", "Adaptive"]

[[variant_values]]
axis = "Theme"
description = "Visual theme of the component"
values = ["Light", "Dark", "Neon", "Pastel", "HighContrast", "Monochrome", "Brand"]

[variant_values.Animation]
values = ["None", "Fade", "Slide", "Pop", "Holographic"]

[variant_values.Density]
values = ["Compact", "Comfortable", "Spacious"]

[variant_values.Theme]
values = ["Light", "Dark", "Neon", "Pastel"]

# Reserved for future expansion: multidimensional composition, tesseract-specific axes, etc.