[config]
 path = "./assets"


[[section]]
title = "Header"
content = "" # defaults to FILE.md

[[section]]
title = "Footer"
content = "" # defaults to FILE.md

[[section]]
title = "Attributions"
content = "" # defaults to FILE.md
